version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
    # env_file: .env
    volumes:
      - .:/opt/marblecutter/
    ports:
      - "8000:8000"
    entrypoint: python
    command: server.py
